name: Testing

on:
  pull_request:
    branches:
#      - '*'         # matches every branch that doesn't contain a '/'
#      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
#      - '!master'   # excludes master

jobs:
  testing:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Linting - Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npx eslint
      - run: yarn install
      - run: yarn test
      
      - name: Archive code coverage clover results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-clover-report
          path: build/coverage/clover.xml

      - name: Archive code coverage html results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-html-report
          path: build/coverage/lcov-report